import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios';

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [numParagraphs, setNumParagraphs] = useState(3);

  useEffect(() => {
    axios.get('/api/hello', {
      params: {
        numParagraphs: numParagraphs,
      }
    })
    .then(response => {
      console.log('🔶 response', '\n', response);
      setResults(response.data.stuff);
    })
  }, [numParagraphs]);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Grateful Ipsum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Grateful Ipsum
        </h1>

        <div>
          <form>
            <input type="textbox" placeholder="# of paragraphs" onChange={(event)=>{setNumParagraphs(event.target.value)}} />
          </form>
        </div>

        <div>
          {results.map(result => (
            <p>{result}</p>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
            💀
          </span>
        </a>
      </footer>
    </div>
  )
}
